== Kontextabgrenzung

=== Fachlicher Kontext
Die folgende Tabelle und Abbildung zeigen die Ein- und Ausgaben von ToneMate und den direkten Kommunikationspartnern.

[%autowidth]
|===
|Kommunikationspartner |Eingabe zu ToneMate |Ausgabe von ToneMate

|Student
a|* Fortschritte in Trainingssektion 
 * Abspeichern von Partituren 
 * Eintragen von Kalenderterminen mit potentiellen Kommentaren 
 * Gezieltes Verändern der App über die Einstellungen 
 Manuelle Synchronisation der Lokalen Daten mit den Daten Im Universitätssystem
 * Login Daten für Login
a|* Möglich zu erziehlender Forschritt in der Trainingssektion über das trainieren mit der App 
 * Speicherung und dementsprechend mögliche on-demand Abrufung von gespeicherten Partituren 
 * Pushbenachrichitungen zu gesetzten Terminen

|Microsoft Authentication
a| * Berechtigungscode und OAuth Bearer Token für Login. 
a| * Login Daten für Login

|Universitäts-System
a|* Updaten der gespeicherten Partituren welche von Dozenten hochgeladen werden
a|* Trainingsfortschritt von Studenten zur Einsicht der Dozenten
|===

plantuml::diagrams/fachlicher_kontext.puml[]

=== Technischer Kontext
Der technische Kontext in der folgenden Tabelle und Abbildung zeigen die einzelnen Kommunikationspartner und dessen, zur Kommunikation verwendeten, Protokolle mit ToneMate.

|===
|Kommunikationskanal |Beschreibung |Protokolle / Technologien

|Student
|Physische Nutzung der mobilen Anwendung auf mobilem Endgerät.
|Handy App / Physische Nutzung

|Microsoft Authentication
|Externe Schnittstelle zur Durchführung der eigentlichen Authentifizierung und Autorisierung. Übergabe von Nutzercredentials, Erhalt von Tokens.
|HTTPS, REST

|Universitätssystem
|Externes System für Informationsaustausch und -abgleich. 
|HTTPS, REST
|===

plantuml::diagrams/technischer_kontext.puml[]