== Kontextabgrenzung

=== Fachlicher Kontext

[%autowidth]
|===
|Kommunikationspartner |Eingabe zu ToneMate |Ausgabe von ToneMate

|Student
a|* Fortschritte in Trainingssektion 
 * Abspeichern von Partituren 
 * Eintragen von Kalenderterminen mit potentiellen Kommentaren 
 * Gezieltes Verändern der App über die Einstellungen 
 Manuelle Synchronisation der Lokalen Daten mit den Daten Im Universitätssystem
 * Login Daten für Login
a|* Möglich zu erziehlender Forschritt in der Trainingssektion über das trainieren mit der App 
 * Speicherung und dementsprechend mögliche on-demand Abrufung von gespeicherten Partituren 
 * Pushbenachrichitungen zu gesetzten Terminen

|Microsoft Authentication
a| * Berechtigungscode und Oauth Bearer Token für Login. 
a| * Login Daten für Login

|Universitäts-System
a|* Updaten der gespeicherten Partituren welche von Dozenten hochgeladen werden
a|* Trainingsfortschritt von Studenten zur Einsicht der Dozenten
|===

plantuml::../diagrams/fachlicher_kontext.puml[]

=== Technischer Kontext

[plantuml]
....
@startuml
!include <C4/C4_Context>

caption TechnischerKontext

Person(student, "Student")

System(toneMate, "ToneMate", $type="React Native")
System_Ext(oauth, "Microsoft Identity Platform")
System_Ext(uni, "Universitäts-System")

Rel_D(toneMate, uni, "Internet / REST / Uni-API")
Rel_L(uni, oauth, "Internet / REST / MSAL-API")
Rel_D(toneMate, oauth, "Internet / REST / MSAL-API")

Rel_R(student, toneMate, "benutzt")

@enduml
....

|===
|Kommunikationskanal |Beschreibung |Protokolle / Technologien

|Student
|Physische Nutzung der mobilen Anwendung auf mobilem Endgerät.
|Handy App / Physische Nutzung

|Microsoft Authentication
|Externe Schnittstelle zur Durchführung der eigentlichen Authentifizierung und Autorisierung. Übergabe von Nutzercredentials, Erhalt von Tokens.
|HTTPS, REST

|Universitäts-System
|
|HTTPS, REST
|===
