== Laufzeitsicht

=== Benutzer Login

Die folgende Grafik zeigt die Kommunikation mit Microsoft als Identity Provider. Durch die Randbedingung TM-01 (siehe <<Funktionale Anforderungen>>) wird definiert, dass Microsoft als Authentication zu verwenden ist. Die Grafik soll zur schnellen Übersicht dienen, eine ausführliche Beschreibung ist in der https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#protocol-details[Microsoft Dokumentation] zu finden.

plantuml::diagrams/laufzeit_login.puml[]

=== Synchronisierung Level Fortschritt

Die folgende Grafik zeigt die Synchronisierung des Level Fortschritts beim öffnen von ToneMate oder beim benutzen der Synchronisierungsfunktion in den Einstellungen.

plantuml::diagrams/laufzeit_levelStart.puml[]

Die folgende Grafik zeigt die Synchronisierung des Level Fortschritts beim abschließen eines Levels

plantuml::diagrams/laufzeit_levelWeiter.puml[]

=== Synchronisierung Partituren

Die folgende Grafik zeigt die Synchronisierung der Partituren aus dem Universitätssystem, welche von den Dozenten hochgeladen werden können.

plantuml::diagrams/laufzeit_partituren.puml[]
