@startuml
!include <C4/C4_Context>

caption Fachliches Gesamtsystem

Person(student, "Student")

System(toneMate, "ToneMate", $type="React Native")
System_Ext(oauth, "Microsoft Identity Platform")
System_Ext(uni, "Universitätssystem")

Rel_D(toneMate, uni, "benutzt")
Rel_L(uni, oauth, "benutzt")
Rel_D(toneMate, oauth, "nutzt login von")

Rel_R(student, toneMate, "benutzt")

@enduml
