@startuml
autonumber
participant ToneMate [
    =ToneMate
]

participant Uni [
    =Universität
]

ToneMate -> Uni: Fragt die Level-Daten ab
ToneMate <-- Uni: Gibt die Level-Daten zurück

ToneMate -> ToneMate: Verleicht den Level Fortschritt mit den lokalen Daten

autonumber stop
alt Universitätsdaten sind weiter fortgeschritten

    ToneMate -> ToneMate: Überschreibt lokale Daten mit den neuen Daten

else lokale Daten sind weiter fortgeschritten

    ToneMate -> Uni: Sendet lokale Daten

end

@enduml