@startuml
autonumber
participant ToneMate [
    =ToneMate
]

participant Uni [
    =Universität
]

ToneMate -> ToneMate: Speichert die Daten lokal

autonumber stop
alt Universitäts-System erreichbar

    ToneMate -> Uni: Sendet lokale Daten

else Verbindungstimeout oder Status Code 5xx

    ToneMate -> ToneMate: Deaktiviert für 5 min synchronisation 
    
end

@enduml