@startuml

caption Login

autonumber
participant ToneMate [
    =ToneMate
]
participant MicrosoftAuth [
    =Microsoft
    ----
    ""/authorize""
]
participant MicrosoftToken [
    =Microsoft
    ----
    ""/token""
]
participant Uni [
    =Universität
]

ToneMate -> MicrosoftAuth: Login mit dem Universitäts Microsoft Account
ToneMate <-- MicrosoftAuth: Gibt Berechtigungscode zurück

ToneMate -> MicrosoftToken: Fragt OAuth bearer token mit Zugabe von dem Berechtigungscode, Client-ID und Client-Secret an
ToneMate <-- MicrosoftToken: Gibt OAuth bearer token zurück

ToneMate -> Uni: Fragt Ressourcen mit dem bearer token an
Uni -> Uni: Validiert bearer token
ToneMate <-- Uni: Gibt Ressourcen zurück
@enduml
