@startuml

caption Level Synchronisation beim Fortschritt

autonumber
participant ToneMate [
    =ToneMate
]

participant Uni [
    =Universität
]

ToneMate -> ToneMate: Speichert die Daten lokal

autonumber stop
alt Universitätssystem erreichbar

    ToneMate -> Uni: Sendet lokale Daten

else Verbindungstimeout oder Status Code 5xx

    ToneMate -> ToneMate: Deaktiviert für 5 min synchronisation

end

@enduml
