ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]
== Bausteinsicht

ifdef::arc42help[]

endif::arc42help[]

=== Whitebox Gesamtsystem

ifdef::arc42help[]

endif::arc42help[]

[plantuml]
....
@startuml
!include <C4/C4_Context>

Person(student, "Student")
Person_Ext(personal, "Hochschul Personal")

System(toneMate, "ToneMate", $type="React Native")
System_Ext(oauth, "Microsoft Identity Platform")
System_Ext(uni, "Universitäts-System")

Rel_D(toneMate, uni, "benutzt", "REST")
Rel_L(uni, oauth, "benutzt")
Rel_D(toneMate, oauth, "nutzt login von")

Rel_R(student, toneMate, "benutzt")
Rel_L(personal, uni, "benutzt")

@enduml
....

Begründung::
ToneMate als Lern-App verwendet eine Anbindung an das Universitäts-System um den Vortschritt zu speichen. Das Personal der Universität kann ebenfalls auf den Vortschritt der Studenten zugreifen. Damit sich die Studenten über die über Microsoft bereitgestellten Universitäts-Accounts nutzten zu können, wird Microsoft als OAuth Provider eingesetzt.

Enthaltene Bausteine::

[%autowidth]
|===
|Baustein |Schnittstellen

|ToneMate
|Universitäts-System, Microsoft Identity Platform
|===

// Wichtige Schnittstellen::


=== Ebene 2

ifdef::arc42help[]

endif::arc42help[]

==== Whitebox ToneMate

ifdef::arc42help[]

endif::arc42help[]

[plantuml]
....
@startuml
!include <C4/C4_Container>

System_Boundary(phone, "Smartphone") {
    Container_Boundary(toneMate, "ToneMate") {
        Container(werkzeuge, "Werkzeuge")
        Container(kalender, "Kalender")
        Container(training, "Training")
        Container(accountManager, "Account Manager")
        Container(api, "API Layer")

        Rel(training, accountManager, "benutzt")
        Rel(werkzeuge, accountManager, "benutzt")
        Rel(kalender, accountManager, "benutzt")
        Rel(accountManager, api, "benutzt")
    }
    Container_Ext(dateiSystem, "Dateisystem")
    Container_Ext(kalenderExt, "Nativer Kalender")

    Rel(kalender, kalenderExt, "speichert in")
    Rel(kalender, dateiSystem, "speichert in")
    Rel(werkzeuge, dateiSystem, "speichert in")
    Rel(training, dateiSystem, "speichert in")
}
System_Ext(oauth, "Microsoft Identity Platform")
System_Ext(uni, "Universitäts-System")

Rel(api, uni, "benutzt", "REST")
Rel_L(uni, oauth, "benutzt")
Rel(api, oauth, "nutzt login von")

@enduml
....

Begründung::


Enthaltene Bausteine::

[%autowidth]
|===
|Baustein |Schnittstellen

|Training
|

|Werkzeuge
|

|Kalender
|

|Account Manager
|

|API Layer
|
|===

// Wichtige Schnittstellen::


=== Ebene 3

ifdef::arc42help[]

endif::arc42help[]

==== Whitebox Training

ifdef::arc42help[]

endif::arc42help[]

[plantuml]
....
@startuml
!include <C4/C4_Component>

Container_Boundary(toneMate, "ToneMate") {
    Container_Boundary(training, "Training") {
        Component(relativerPitch, "Relativer Pitch")
        Component(akkordBestimmung, "Akkord Bestimmung")
        Component(intervalBestimmung, "Interval Bestimmung")
        Component(speicherManager, "Speicher Manager")

        Rel(relativerPitch, speicherManager, "benutzt")
        Rel(akkordBestimmung, speicherManager, "benutzt")
        Rel(intervalBestimmung, speicherManager, "benutzt")
    }
    Container(api, "API Layer")

    Rel(speicherManager, api, "benutzt")
}
Container_Ext(dateiSystem, "Dateisystem")

Rel(speicherManager, dateiSystem, "speichert in")

@enduml
....

Begründung::


Enthaltene Bausteine::

[%autowidth]
|===
|Baustein |Schnittstellen

|Training
|
|===

// Wichtige Schnittstellen::


==== Whitebox <_Baustein x.2_>

_<Whitebox-Template>_

==== Whitebox <_Baustein y.1_>

_<Whitebox-Template>_
