ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]
== Bausteinsicht

ifdef::arc42help[]

endif::arc42help[]

=== Whitebox Gesamtsystem

ifdef::arc42help[]

endif::arc42help[]

// [mermaid]
// ....
// architecture-beta
//     service app[ToneMate]
//     service calender_ext[Nativer Kalender]
//     service file_ext[Dateisystem]

//     junction external

//     app:B -- T:external
//     external:L -- R:calender_ext
//     external:R -- L:file_ext
// ....

[plantuml]
....
@startuml
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(student, "Student")
Person_Ext(personal, "Hochschul Personal")

System(toneMate, "ToneMate", $type="React Native")
System_Ext(oauth, "Microsoft Identity Platform")
System_Ext(uni, "Universitäts-System")

Rel_D(toneMate, uni, "benutzt", "REST")
Rel_L(uni, oauth, "benutzt")
Rel_D(toneMate, oauth, "nutzt login von")

Rel_R(student, toneMate, "benutzt")
Rel_L(personal, uni, "benutzt")

@enduml
....

Begründung::
ToneMate als Lern-App verwendet eine Anbindung an das Universitäts-System um den Vortschritt zu speichen. Das Personal der Universität kann ebenfalls auf den Vortschritt der Studenten zugreifen. Damit sich die Studenten über die über Microsoft bereitgestellten Universitäts-Accounts nutzten zu können, wird Microsoft als OAuth Provider eingesetzt.

Enthaltene Bausteine::

[%autowidth]
|===
|Baustein |Schnittstellen

|ToneMate
|Universitäts-System, Microsoft Identity Platform
|===

// Wichtige Schnittstellen::

=== Ebene 2

ifdef::arc42help[]

endif::arc42help[]

==== Whitebox ToneMate

ifdef::arc42help[]

endif::arc42help[]

[plantuml]
....
@startuml
!include <C4/C4_Container>

System_Boundary(phone, "Smartphone") {
    Container_Boundary(toneMate, "ToneMate") {
        Container(training, "Training")
        Container(werkzeuge, "Werkzeuge")
        Container(kalender, "Kalender")
        Container(accountManager, "Account Manager")
        Container(api, "API Layer")

        Rel_D(training, accountManager, "benutzt")
        Rel_D(werkzeuge, accountManager, "benutzt")
        Rel_D(kalender, accountManager, "benutzt")
        Rel_D(accountManager, api, "benutzt")
    }
    Container_Ext(fileSystem, "File System")
    Container_Ext(kalenderExt, "Nativer Kalender")

    Rel_L(kalender, kalenderExt, "speichert in")
    Rel_L(kalender, fileSystem, "speichert in")
    Rel_L(werkzeuge, fileSystem, "greift zu")
}
System_Ext(oauth, "Microsoft Identity Platform")
System_Ext(uni, "Universitäts-System")
@enduml
....

==== Whitebox _<Baustein 2>_

_<Whitebox-Template>_

...

==== Whitebox _<Baustein m>_

_<Whitebox-Template>_

=== Ebene 3

ifdef::arc42help[]

endif::arc42help[]

==== Whitebox <_Baustein x.1_>

ifdef::arc42help[]

endif::arc42help[]

_<Whitebox-Template>_

==== Whitebox <_Baustein x.2_>

_<Whitebox-Template>_

==== Whitebox <_Baustein y.1_>

_<Whitebox-Template>_
