ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Laufzeitsicht

ifdef::arc42help[]

endif::arc42help[]

=== Benutzer Login

Die folgende Grafik zeigt die Kommunikation mit Microsoft als Identity Provider. Durch die Randbedingung xref:#section-architecture-constraints[TE-01] wird definiert, dass Microsoft als Authentication zu verwenden ist. Die Grafik soll zur schnellen Übersicht dienen, ein ausführliche Beschreibung ist in der https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#protocol-details[Microsoft Dokumentation] zu finden.

[plantuml]
....
@startuml
autonumber
participant ToneMate [
    =ToneMate
]
participant MicrosoftAuth [
    =Microsoft
    ----
    ""/authorize""
]
participant MicrosoftToken [
    =Microsoft
    ----
    ""/token""
]
participant Uni [
    =Universität
]

ToneMate -> MicrosoftAuth: Login mit dem Universitäts Microsoft Account
ToneMate <-- MicrosoftAuth: Gibt Berechtigungscode zurück

ToneMate -> MicrosoftToken: Fragt Outh bearer token mit Zugabe von dem Berechtigungscode, Client-ID und Client-Secret an
ToneMate <-- MicrosoftToken: Gibt Oauth bearer token zurück

ToneMate -> Uni: Fragt Ressourcen mit dem bearer token an
Uni -> Uni: Validiert bearer token
ToneMate <-- Uni: Gitb Ressourcen zurück
@enduml
....
// *  <hier Besonderheiten bei dem Zusammenspiel der Bausteine in diesem Szenario erläutern>

// === _<Bezeichnung Laufzeitszenario 2>_


// === _<Bezeichnung Laufzeitszenario n>_

