name: Build docx and pdf

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true
      - name: Asciidoctor Setup
        uses: reitzig/actions-asciidoctor@v2.0.2
      - run: gem install asciidoctor-pdf
      - run: gem install asciidoctor-diagram
      - run: npm install -g @mermaid-js/mermaid-cli
      - run: ./bin/build.sh -v ./arc42-template.adoc
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: ./build
