name: Build docx and pdf

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - run: sudo apt-get install plantuml librsvg2-bin
      - run: npm install -g @mermaid-js/mermaid-cli
      - run: make clean pdf
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: ./build/arc42-template.*
