name: Build docx and pdf

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.218.0
        with:
          bundler-cache: true
      - name: Asciidoctor Setup
        uses: reitzig/actions-asciidoctor@v2.0.2
      - run: ./bin/build.sh -v ./arc42-template.adoc
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: documents
          path: ./build
